name: max_inventory_scanner
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  mobile_scanner: ^4.0.1
  intl: ^0.19.0
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.2.3
  flutter_easyloading: ^3.0.5
  image_picker: ^1.1.2
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.1.0
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.3
  path: ^1.9.0
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - lottie/
    - assets/

  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope.ttf
        - asset: fonts/Manrope-ExtraBold.ttf
        - asset: fonts/Manrope-ExtraLight.ttf
        - asset: fonts/Manrope-Light.ttf
        - asset: fonts/Manrope-Medium.ttf
        - asset: fonts/Manrope-Regular.ttf
        - asset: fonts/Manrope-SemiBold.ttf